use_frameworks!

platform :ios, '10.0'

target 'DataSailExtension_Example' do
  pod 'DataSailExtension', :path => '../'

  target 'DataSailExtension_Tests' do
    inherit! :search_paths

    
  end
end
